### ISSUE TITLE
Check and Review the DEV merge request of Wille

### ISSUE THREAD

**Issue by Akhilraj03-Github** [hvkone/wordfinder#46]
As Dev merge request is showing some errors, please check and review it

**Comment by hvkone** [comment]
Are you talking about the current outstanding pull request?

**Comment by Akhilraj03-Github** [comment]
I am talking about the DEV #45 merge request wille, 
If it's done, let me know.

**Comment by hvkone** [comment]
Yes, it should be fixed now. The error was a workflow action that would not pass, but I disabled it.

**Comment by Akhilraj03-Github** [comment]
Thanks, wille.
Done, Issue resolved.
