### ISSUE TITLE
one cluster bug when scoring to result 

### ISSUE THREAD

**Issue by jackzhenguo** [hvkone/wordfinder#53]
The bug that we demonstrated French sentence clustering in today's class has been solved. 

The DBSCAN algorithm thinks that the optimal number of clusters is 1, but when we use silhouette method to score the clustering result, there is only one class, so it can't calculate the euclidean distance, so it triggers a bug.

metrics.silhouette_ score(self.X, labels, metric='euclidean')

**Comment by jackzhenguo** [comment]
This issue has been solved

**Comment by Akhilraj03-Github** [comment]
Thanks and Good Work, Zhen.

**Comment by Akhilraj03-Github** [comment]
@hvkone Is it still getting an  error wille,
Or is it resolved. So, we can close the Issue.
As Final Release date is coming up this Friday

**Comment by Akhilraj03-Github** [comment]
Is it still haven't resolved?

**Comment by Akhilraj03-Github** [comment]
I think it is resolved.
Good work guys.
Good Job.
